# Generated by Django 3.1.4 on 2022-09-27 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ManagerModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('company', models.CharField(max_length=250)),
                ('mobile', models.IntegerField()),
                ('city', models.CharField(max_length=250)),
                ('created_by_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerModel.manager')),
            ],
        ),
    ]
